### ISSUE TITLE
Refresh Token Not Working

### ISSUE THREAD

**Issue by ehalsey** [IntuitDeveloper/SampleApp-Dotnet_Payments#1]
I'm getting a different error message when the access_token needs to be refreshed.  I'm getting "The remote server returned an error: (401) Unauthorized." but the repo uses "UnAuthorized-401".  Also, the refresh process doesn't appear to be working for me even after I change the error message check.  Ends up in never ending recursion.  Any suggestions very much appreciated.

**Comment by nimisha84** [comment]
Can you use fiddler and run it alongside your code? Add the logged request and response from raw tab.
Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers. 

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler. 

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by nimisha84** [comment]
Refresh token can end up in recursion only if the error persists. Please send me the request and response so that I can tell you what exactly needs to be changed.

**Comment by ehalsey** [comment]
Here's the capture file. Thanks for looking in to this.
[OAuth2-Dotnet_Payments_w_Refresh.zip](https://github.com/IntuitDeveloper/OAuth2-Dotnet_Payments/files/1265580/OAuth2-Dotnet_Payments_w_Refresh.zip)

**Comment by nimisha84** [comment]
Can you go to performRefreshToken function and add these 2 lines after
output("Access token refreshed.");
      dictionary["accessToken"] = refereshtokenCallResponse.AccessToken;
            dictionary["refreshToken"] = refereshtokenCallResponse.RefreshToken;

Also, in paymentsApiCall function change the ex.Message to compare like this below -
 if (ex.Message == "The remote server returned an error: (401) Unauthorized.")

This should hopefully resolve your issue. Let me know if this works and I will update the github code.

**Comment by ehalsey** [comment]
That was it.

**Comment by ehalsey** [comment]
@nimisha84, looks like someone included the bin and obj\Debug files in the repro.  Most repros don't include these.
![2017-08-30_20-46-00](https://user-images.githubusercontent.com/14900980/29905596-7e36542a-8dc4-11e7-91fc-da3bc565a471.png)

**Comment by nimisha84** [comment]
Thanks for the feedback. Will try to remove them from future checkins. Closing this issue
